// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: adventureworks.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace AdventureWorks {

  /// <summary>Holder for reflection information generated from adventureworks.proto</summary>
  public static partial class AdventureworksReflection {

    #region Descriptor
    /// <summary>File descriptor for adventureworks.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AdventureworksReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRhZHZlbnR1cmV3b3Jrcy5wcm90bxIOYWR2ZW50dXJlV29ya3MaHmdvb2ds",
            "ZS9wcm90b2J1Zi9kdXJhdGlvbi5wcm90bxofZ29vZ2xlL3Byb3RvYnVmL3Rp",
            "bWVzdGFtcC5wcm90byKAAwoFT3JkZXISFgoOc2FsZXNfb3JkZXJfaWQYASAB",
            "KAUSGgoSc2FsZXNfb3JkZXJfbnVtYmVyGAIgASgJEh0KFXB1cmNoYXNlX29y",
            "ZGVyX251bWJlchgDIAEoCRIuCgpvcmRlcl9kYXRlGAQgASgLMhouZ29vZ2xl",
            "LnByb3RvYnVmLlRpbWVzdGFtcBItCglzaGlwX2RhdGUYBSABKAsyGi5nb29n",
            "bGUucHJvdG9idWYuVGltZXN0YW1wEhcKD2lzX29ubGluZV9vcmRlchgGIAEo",
            "CBIRCglzdWJfdG90YWwYByABKAESEQoJdG90YWxfZHVlGAggASgBEikKCHBy",
            "b2R1Y3RzGAkgAygLMhcuYWR2ZW50dXJlV29ya3MuUHJvZHVjdBIqCghjdXN0",
            "b21lchgKIAEoCzIYLmFkdmVudHVyZVdvcmtzLkN1c3RvbWVyEi8KC2NyZWRp",
            "dF9jYXJkGAsgASgLMhouYWR2ZW50dXJlV29ya3MuQ3JlZGl0Q2FyZCKaAQoH",
            "UHJvZHVjdBISCgpwcm9kdWN0X2lkGAEgASgFEgwKBG5hbWUYAiABKAkSFgoO",
            "cHJvZHVjdF9udW1iZXIYAyABKAkSDQoFY29sb3IYBCABKAkSFQoNc3RhbmRh",
            "cmRfY29zdBgFIAEoARISCgpsaXN0X3ByaWNlGAYgASgBEgwKBHNpemUYByAB",
            "KAkSDQoFd2VpZ2gYCCABKAEiXgoIQ3VzdG9tZXISEgoKZmlyc3RfbmFtZRgB",
            "IAEoCRITCgttaWRkbGVfbmFtZRgCIAEoCRIRCglsYXN0X25hbWUYAyABKAkS",
            "FgoOYWNjb3VudF9udW1iZXIYBCABKAkiRgoKQ3JlZGl0Q2FyZBITCgtjYXJk",
            "X251bWJlchgBIAEoAxIRCglleHBfbW9udGgYAiABKAUSEAoIZXhwX3llYXIY",
            "AyABKAUiJgoMT3JkZXJSZXF1ZXN0EhYKDnNhbGVzX29yZGVyX2lkGAEgASgF",
            "IjUKDU9yZGVyUmVzcG9uc2USJAoFb3JkZXIYASABKAsyFS5hZHZlbnR1cmVX",
            "b3Jrcy5PcmRlcjJUCgxPcmRlclNlcnZpY2USRAoDR2V0EhwuYWR2ZW50dXJl",
            "V29ya3MuT3JkZXJSZXF1ZXN0Gh0uYWR2ZW50dXJlV29ya3MuT3JkZXJSZXNw",
            "b25zZSIAYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.DurationReflection.Descriptor, global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::AdventureWorks.Order), global::AdventureWorks.Order.Parser, new[]{ "SalesOrderId", "SalesOrderNumber", "PurchaseOrderNumber", "OrderDate", "ShipDate", "IsOnlineOrder", "SubTotal", "TotalDue", "Products", "Customer", "CreditCard" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AdventureWorks.Product), global::AdventureWorks.Product.Parser, new[]{ "ProductId", "Name", "ProductNumber", "Color", "StandardCost", "ListPrice", "Size", "Weigh" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AdventureWorks.Customer), global::AdventureWorks.Customer.Parser, new[]{ "FirstName", "MiddleName", "LastName", "AccountNumber" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AdventureWorks.CreditCard), global::AdventureWorks.CreditCard.Parser, new[]{ "CardNumber", "ExpMonth", "ExpYear" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AdventureWorks.OrderRequest), global::AdventureWorks.OrderRequest.Parser, new[]{ "SalesOrderId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::AdventureWorks.OrderResponse), global::AdventureWorks.OrderResponse.Parser, new[]{ "Order" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Order : pb::IMessage<Order>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Order> _parser = new pb::MessageParser<Order>(() => new Order());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Order> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AdventureWorks.AdventureworksReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Order() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Order(Order other) : this() {
      salesOrderId_ = other.salesOrderId_;
      salesOrderNumber_ = other.salesOrderNumber_;
      purchaseOrderNumber_ = other.purchaseOrderNumber_;
      orderDate_ = other.orderDate_ != null ? other.orderDate_.Clone() : null;
      shipDate_ = other.shipDate_ != null ? other.shipDate_.Clone() : null;
      isOnlineOrder_ = other.isOnlineOrder_;
      subTotal_ = other.subTotal_;
      totalDue_ = other.totalDue_;
      products_ = other.products_.Clone();
      customer_ = other.customer_ != null ? other.customer_.Clone() : null;
      creditCard_ = other.creditCard_ != null ? other.creditCard_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Order Clone() {
      return new Order(this);
    }

    /// <summary>Field number for the "sales_order_id" field.</summary>
    public const int SalesOrderIdFieldNumber = 1;
    private int salesOrderId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SalesOrderId {
      get { return salesOrderId_; }
      set {
        salesOrderId_ = value;
      }
    }

    /// <summary>Field number for the "sales_order_number" field.</summary>
    public const int SalesOrderNumberFieldNumber = 2;
    private string salesOrderNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string SalesOrderNumber {
      get { return salesOrderNumber_; }
      set {
        salesOrderNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "purchase_order_number" field.</summary>
    public const int PurchaseOrderNumberFieldNumber = 3;
    private string purchaseOrderNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string PurchaseOrderNumber {
      get { return purchaseOrderNumber_; }
      set {
        purchaseOrderNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "order_date" field.</summary>
    public const int OrderDateFieldNumber = 4;
    private global::Google.Protobuf.WellKnownTypes.Timestamp orderDate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp OrderDate {
      get { return orderDate_; }
      set {
        orderDate_ = value;
      }
    }

    /// <summary>Field number for the "ship_date" field.</summary>
    public const int ShipDateFieldNumber = 5;
    private global::Google.Protobuf.WellKnownTypes.Timestamp shipDate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp ShipDate {
      get { return shipDate_; }
      set {
        shipDate_ = value;
      }
    }

    /// <summary>Field number for the "is_online_order" field.</summary>
    public const int IsOnlineOrderFieldNumber = 6;
    private bool isOnlineOrder_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsOnlineOrder {
      get { return isOnlineOrder_; }
      set {
        isOnlineOrder_ = value;
      }
    }

    /// <summary>Field number for the "sub_total" field.</summary>
    public const int SubTotalFieldNumber = 7;
    private double subTotal_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double SubTotal {
      get { return subTotal_; }
      set {
        subTotal_ = value;
      }
    }

    /// <summary>Field number for the "total_due" field.</summary>
    public const int TotalDueFieldNumber = 8;
    private double totalDue_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double TotalDue {
      get { return totalDue_; }
      set {
        totalDue_ = value;
      }
    }

    /// <summary>Field number for the "products" field.</summary>
    public const int ProductsFieldNumber = 9;
    private static readonly pb::FieldCodec<global::AdventureWorks.Product> _repeated_products_codec
        = pb::FieldCodec.ForMessage(74, global::AdventureWorks.Product.Parser);
    private readonly pbc::RepeatedField<global::AdventureWorks.Product> products_ = new pbc::RepeatedField<global::AdventureWorks.Product>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::AdventureWorks.Product> Products {
      get { return products_; }
    }

    /// <summary>Field number for the "customer" field.</summary>
    public const int CustomerFieldNumber = 10;
    private global::AdventureWorks.Customer customer_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AdventureWorks.Customer Customer {
      get { return customer_; }
      set {
        customer_ = value;
      }
    }

    /// <summary>Field number for the "credit_card" field.</summary>
    public const int CreditCardFieldNumber = 11;
    private global::AdventureWorks.CreditCard creditCard_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AdventureWorks.CreditCard CreditCard {
      get { return creditCard_; }
      set {
        creditCard_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Order);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Order other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SalesOrderId != other.SalesOrderId) return false;
      if (SalesOrderNumber != other.SalesOrderNumber) return false;
      if (PurchaseOrderNumber != other.PurchaseOrderNumber) return false;
      if (!object.Equals(OrderDate, other.OrderDate)) return false;
      if (!object.Equals(ShipDate, other.ShipDate)) return false;
      if (IsOnlineOrder != other.IsOnlineOrder) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(SubTotal, other.SubTotal)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(TotalDue, other.TotalDue)) return false;
      if(!products_.Equals(other.products_)) return false;
      if (!object.Equals(Customer, other.Customer)) return false;
      if (!object.Equals(CreditCard, other.CreditCard)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SalesOrderId != 0) hash ^= SalesOrderId.GetHashCode();
      if (SalesOrderNumber.Length != 0) hash ^= SalesOrderNumber.GetHashCode();
      if (PurchaseOrderNumber.Length != 0) hash ^= PurchaseOrderNumber.GetHashCode();
      if (orderDate_ != null) hash ^= OrderDate.GetHashCode();
      if (shipDate_ != null) hash ^= ShipDate.GetHashCode();
      if (IsOnlineOrder != false) hash ^= IsOnlineOrder.GetHashCode();
      if (SubTotal != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(SubTotal);
      if (TotalDue != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(TotalDue);
      hash ^= products_.GetHashCode();
      if (customer_ != null) hash ^= Customer.GetHashCode();
      if (creditCard_ != null) hash ^= CreditCard.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SalesOrderId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SalesOrderId);
      }
      if (SalesOrderNumber.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SalesOrderNumber);
      }
      if (PurchaseOrderNumber.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PurchaseOrderNumber);
      }
      if (orderDate_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(OrderDate);
      }
      if (shipDate_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(ShipDate);
      }
      if (IsOnlineOrder != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsOnlineOrder);
      }
      if (SubTotal != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(SubTotal);
      }
      if (TotalDue != 0D) {
        output.WriteRawTag(65);
        output.WriteDouble(TotalDue);
      }
      products_.WriteTo(output, _repeated_products_codec);
      if (customer_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(Customer);
      }
      if (creditCard_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(CreditCard);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SalesOrderId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SalesOrderId);
      }
      if (SalesOrderNumber.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(SalesOrderNumber);
      }
      if (PurchaseOrderNumber.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(PurchaseOrderNumber);
      }
      if (orderDate_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(OrderDate);
      }
      if (shipDate_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(ShipDate);
      }
      if (IsOnlineOrder != false) {
        output.WriteRawTag(48);
        output.WriteBool(IsOnlineOrder);
      }
      if (SubTotal != 0D) {
        output.WriteRawTag(57);
        output.WriteDouble(SubTotal);
      }
      if (TotalDue != 0D) {
        output.WriteRawTag(65);
        output.WriteDouble(TotalDue);
      }
      products_.WriteTo(ref output, _repeated_products_codec);
      if (customer_ != null) {
        output.WriteRawTag(82);
        output.WriteMessage(Customer);
      }
      if (creditCard_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(CreditCard);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SalesOrderId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SalesOrderId);
      }
      if (SalesOrderNumber.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SalesOrderNumber);
      }
      if (PurchaseOrderNumber.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(PurchaseOrderNumber);
      }
      if (orderDate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(OrderDate);
      }
      if (shipDate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ShipDate);
      }
      if (IsOnlineOrder != false) {
        size += 1 + 1;
      }
      if (SubTotal != 0D) {
        size += 1 + 8;
      }
      if (TotalDue != 0D) {
        size += 1 + 8;
      }
      size += products_.CalculateSize(_repeated_products_codec);
      if (customer_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Customer);
      }
      if (creditCard_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreditCard);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Order other) {
      if (other == null) {
        return;
      }
      if (other.SalesOrderId != 0) {
        SalesOrderId = other.SalesOrderId;
      }
      if (other.SalesOrderNumber.Length != 0) {
        SalesOrderNumber = other.SalesOrderNumber;
      }
      if (other.PurchaseOrderNumber.Length != 0) {
        PurchaseOrderNumber = other.PurchaseOrderNumber;
      }
      if (other.orderDate_ != null) {
        if (orderDate_ == null) {
          OrderDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        OrderDate.MergeFrom(other.OrderDate);
      }
      if (other.shipDate_ != null) {
        if (shipDate_ == null) {
          ShipDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        ShipDate.MergeFrom(other.ShipDate);
      }
      if (other.IsOnlineOrder != false) {
        IsOnlineOrder = other.IsOnlineOrder;
      }
      if (other.SubTotal != 0D) {
        SubTotal = other.SubTotal;
      }
      if (other.TotalDue != 0D) {
        TotalDue = other.TotalDue;
      }
      products_.Add(other.products_);
      if (other.customer_ != null) {
        if (customer_ == null) {
          Customer = new global::AdventureWorks.Customer();
        }
        Customer.MergeFrom(other.Customer);
      }
      if (other.creditCard_ != null) {
        if (creditCard_ == null) {
          CreditCard = new global::AdventureWorks.CreditCard();
        }
        CreditCard.MergeFrom(other.CreditCard);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SalesOrderId = input.ReadInt32();
            break;
          }
          case 18: {
            SalesOrderNumber = input.ReadString();
            break;
          }
          case 26: {
            PurchaseOrderNumber = input.ReadString();
            break;
          }
          case 34: {
            if (orderDate_ == null) {
              OrderDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(OrderDate);
            break;
          }
          case 42: {
            if (shipDate_ == null) {
              ShipDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ShipDate);
            break;
          }
          case 48: {
            IsOnlineOrder = input.ReadBool();
            break;
          }
          case 57: {
            SubTotal = input.ReadDouble();
            break;
          }
          case 65: {
            TotalDue = input.ReadDouble();
            break;
          }
          case 74: {
            products_.AddEntriesFrom(input, _repeated_products_codec);
            break;
          }
          case 82: {
            if (customer_ == null) {
              Customer = new global::AdventureWorks.Customer();
            }
            input.ReadMessage(Customer);
            break;
          }
          case 90: {
            if (creditCard_ == null) {
              CreditCard = new global::AdventureWorks.CreditCard();
            }
            input.ReadMessage(CreditCard);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SalesOrderId = input.ReadInt32();
            break;
          }
          case 18: {
            SalesOrderNumber = input.ReadString();
            break;
          }
          case 26: {
            PurchaseOrderNumber = input.ReadString();
            break;
          }
          case 34: {
            if (orderDate_ == null) {
              OrderDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(OrderDate);
            break;
          }
          case 42: {
            if (shipDate_ == null) {
              ShipDate = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ShipDate);
            break;
          }
          case 48: {
            IsOnlineOrder = input.ReadBool();
            break;
          }
          case 57: {
            SubTotal = input.ReadDouble();
            break;
          }
          case 65: {
            TotalDue = input.ReadDouble();
            break;
          }
          case 74: {
            products_.AddEntriesFrom(ref input, _repeated_products_codec);
            break;
          }
          case 82: {
            if (customer_ == null) {
              Customer = new global::AdventureWorks.Customer();
            }
            input.ReadMessage(Customer);
            break;
          }
          case 90: {
            if (creditCard_ == null) {
              CreditCard = new global::AdventureWorks.CreditCard();
            }
            input.ReadMessage(CreditCard);
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Product : pb::IMessage<Product>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Product> _parser = new pb::MessageParser<Product>(() => new Product());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Product> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AdventureWorks.AdventureworksReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Product() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Product(Product other) : this() {
      productId_ = other.productId_;
      name_ = other.name_;
      productNumber_ = other.productNumber_;
      color_ = other.color_;
      standardCost_ = other.standardCost_;
      listPrice_ = other.listPrice_;
      size_ = other.size_;
      weigh_ = other.weigh_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Product Clone() {
      return new Product(this);
    }

    /// <summary>Field number for the "product_id" field.</summary>
    public const int ProductIdFieldNumber = 1;
    private int productId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ProductId {
      get { return productId_; }
      set {
        productId_ = value;
      }
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 2;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "product_number" field.</summary>
    public const int ProductNumberFieldNumber = 3;
    private string productNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ProductNumber {
      get { return productNumber_; }
      set {
        productNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "color" field.</summary>
    public const int ColorFieldNumber = 4;
    private string color_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Color {
      get { return color_; }
      set {
        color_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "standard_cost" field.</summary>
    public const int StandardCostFieldNumber = 5;
    private double standardCost_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double StandardCost {
      get { return standardCost_; }
      set {
        standardCost_ = value;
      }
    }

    /// <summary>Field number for the "list_price" field.</summary>
    public const int ListPriceFieldNumber = 6;
    private double listPrice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double ListPrice {
      get { return listPrice_; }
      set {
        listPrice_ = value;
      }
    }

    /// <summary>Field number for the "size" field.</summary>
    public const int SizeFieldNumber = 7;
    private string size_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Size {
      get { return size_; }
      set {
        size_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "weigh" field.</summary>
    public const int WeighFieldNumber = 8;
    private double weigh_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public double Weigh {
      get { return weigh_; }
      set {
        weigh_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Product);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Product other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ProductId != other.ProductId) return false;
      if (Name != other.Name) return false;
      if (ProductNumber != other.ProductNumber) return false;
      if (Color != other.Color) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(StandardCost, other.StandardCost)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(ListPrice, other.ListPrice)) return false;
      if (Size != other.Size) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Weigh, other.Weigh)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (ProductId != 0) hash ^= ProductId.GetHashCode();
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (ProductNumber.Length != 0) hash ^= ProductNumber.GetHashCode();
      if (Color.Length != 0) hash ^= Color.GetHashCode();
      if (StandardCost != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(StandardCost);
      if (ListPrice != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(ListPrice);
      if (Size.Length != 0) hash ^= Size.GetHashCode();
      if (Weigh != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Weigh);
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (ProductId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ProductId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (ProductNumber.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ProductNumber);
      }
      if (Color.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Color);
      }
      if (StandardCost != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(StandardCost);
      }
      if (ListPrice != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(ListPrice);
      }
      if (Size.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Size);
      }
      if (Weigh != 0D) {
        output.WriteRawTag(65);
        output.WriteDouble(Weigh);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (ProductId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ProductId);
      }
      if (Name.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Name);
      }
      if (ProductNumber.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ProductNumber);
      }
      if (Color.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Color);
      }
      if (StandardCost != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(StandardCost);
      }
      if (ListPrice != 0D) {
        output.WriteRawTag(49);
        output.WriteDouble(ListPrice);
      }
      if (Size.Length != 0) {
        output.WriteRawTag(58);
        output.WriteString(Size);
      }
      if (Weigh != 0D) {
        output.WriteRawTag(65);
        output.WriteDouble(Weigh);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (ProductId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ProductId);
      }
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (ProductNumber.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProductNumber);
      }
      if (Color.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Color);
      }
      if (StandardCost != 0D) {
        size += 1 + 8;
      }
      if (ListPrice != 0D) {
        size += 1 + 8;
      }
      if (Size.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Size);
      }
      if (Weigh != 0D) {
        size += 1 + 8;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Product other) {
      if (other == null) {
        return;
      }
      if (other.ProductId != 0) {
        ProductId = other.ProductId;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.ProductNumber.Length != 0) {
        ProductNumber = other.ProductNumber;
      }
      if (other.Color.Length != 0) {
        Color = other.Color;
      }
      if (other.StandardCost != 0D) {
        StandardCost = other.StandardCost;
      }
      if (other.ListPrice != 0D) {
        ListPrice = other.ListPrice;
      }
      if (other.Size.Length != 0) {
        Size = other.Size;
      }
      if (other.Weigh != 0D) {
        Weigh = other.Weigh;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ProductId = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            ProductNumber = input.ReadString();
            break;
          }
          case 34: {
            Color = input.ReadString();
            break;
          }
          case 41: {
            StandardCost = input.ReadDouble();
            break;
          }
          case 49: {
            ListPrice = input.ReadDouble();
            break;
          }
          case 58: {
            Size = input.ReadString();
            break;
          }
          case 65: {
            Weigh = input.ReadDouble();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            ProductId = input.ReadInt32();
            break;
          }
          case 18: {
            Name = input.ReadString();
            break;
          }
          case 26: {
            ProductNumber = input.ReadString();
            break;
          }
          case 34: {
            Color = input.ReadString();
            break;
          }
          case 41: {
            StandardCost = input.ReadDouble();
            break;
          }
          case 49: {
            ListPrice = input.ReadDouble();
            break;
          }
          case 58: {
            Size = input.ReadString();
            break;
          }
          case 65: {
            Weigh = input.ReadDouble();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class Customer : pb::IMessage<Customer>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Customer> _parser = new pb::MessageParser<Customer>(() => new Customer());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Customer> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AdventureWorks.AdventureworksReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Customer() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Customer(Customer other) : this() {
      firstName_ = other.firstName_;
      middleName_ = other.middleName_;
      lastName_ = other.lastName_;
      accountNumber_ = other.accountNumber_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Customer Clone() {
      return new Customer(this);
    }

    /// <summary>Field number for the "first_name" field.</summary>
    public const int FirstNameFieldNumber = 1;
    private string firstName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string FirstName {
      get { return firstName_; }
      set {
        firstName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "middle_name" field.</summary>
    public const int MiddleNameFieldNumber = 2;
    private string middleName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string MiddleName {
      get { return middleName_; }
      set {
        middleName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "last_name" field.</summary>
    public const int LastNameFieldNumber = 3;
    private string lastName_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string LastName {
      get { return lastName_; }
      set {
        lastName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "account_number" field.</summary>
    public const int AccountNumberFieldNumber = 4;
    private string accountNumber_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string AccountNumber {
      get { return accountNumber_; }
      set {
        accountNumber_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Customer);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Customer other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (FirstName != other.FirstName) return false;
      if (MiddleName != other.MiddleName) return false;
      if (LastName != other.LastName) return false;
      if (AccountNumber != other.AccountNumber) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (FirstName.Length != 0) hash ^= FirstName.GetHashCode();
      if (MiddleName.Length != 0) hash ^= MiddleName.GetHashCode();
      if (LastName.Length != 0) hash ^= LastName.GetHashCode();
      if (AccountNumber.Length != 0) hash ^= AccountNumber.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (FirstName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FirstName);
      }
      if (MiddleName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MiddleName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(LastName);
      }
      if (AccountNumber.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AccountNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (FirstName.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(FirstName);
      }
      if (MiddleName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(MiddleName);
      }
      if (LastName.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(LastName);
      }
      if (AccountNumber.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(AccountNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (FirstName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(FirstName);
      }
      if (MiddleName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(MiddleName);
      }
      if (LastName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(LastName);
      }
      if (AccountNumber.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(AccountNumber);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Customer other) {
      if (other == null) {
        return;
      }
      if (other.FirstName.Length != 0) {
        FirstName = other.FirstName;
      }
      if (other.MiddleName.Length != 0) {
        MiddleName = other.MiddleName;
      }
      if (other.LastName.Length != 0) {
        LastName = other.LastName;
      }
      if (other.AccountNumber.Length != 0) {
        AccountNumber = other.AccountNumber;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            FirstName = input.ReadString();
            break;
          }
          case 18: {
            MiddleName = input.ReadString();
            break;
          }
          case 26: {
            LastName = input.ReadString();
            break;
          }
          case 34: {
            AccountNumber = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            FirstName = input.ReadString();
            break;
          }
          case 18: {
            MiddleName = input.ReadString();
            break;
          }
          case 26: {
            LastName = input.ReadString();
            break;
          }
          case 34: {
            AccountNumber = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class CreditCard : pb::IMessage<CreditCard>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CreditCard> _parser = new pb::MessageParser<CreditCard>(() => new CreditCard());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CreditCard> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AdventureWorks.AdventureworksReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreditCard() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreditCard(CreditCard other) : this() {
      cardNumber_ = other.cardNumber_;
      expMonth_ = other.expMonth_;
      expYear_ = other.expYear_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CreditCard Clone() {
      return new CreditCard(this);
    }

    /// <summary>Field number for the "card_number" field.</summary>
    public const int CardNumberFieldNumber = 1;
    private long cardNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long CardNumber {
      get { return cardNumber_; }
      set {
        cardNumber_ = value;
      }
    }

    /// <summary>Field number for the "exp_month" field.</summary>
    public const int ExpMonthFieldNumber = 2;
    private int expMonth_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ExpMonth {
      get { return expMonth_; }
      set {
        expMonth_ = value;
      }
    }

    /// <summary>Field number for the "exp_year" field.</summary>
    public const int ExpYearFieldNumber = 3;
    private int expYear_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int ExpYear {
      get { return expYear_; }
      set {
        expYear_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CreditCard);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CreditCard other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (CardNumber != other.CardNumber) return false;
      if (ExpMonth != other.ExpMonth) return false;
      if (ExpYear != other.ExpYear) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (CardNumber != 0L) hash ^= CardNumber.GetHashCode();
      if (ExpMonth != 0) hash ^= ExpMonth.GetHashCode();
      if (ExpYear != 0) hash ^= ExpYear.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (CardNumber != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CardNumber);
      }
      if (ExpMonth != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ExpMonth);
      }
      if (ExpYear != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ExpYear);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (CardNumber != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(CardNumber);
      }
      if (ExpMonth != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(ExpMonth);
      }
      if (ExpYear != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(ExpYear);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (CardNumber != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(CardNumber);
      }
      if (ExpMonth != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ExpMonth);
      }
      if (ExpYear != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ExpYear);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CreditCard other) {
      if (other == null) {
        return;
      }
      if (other.CardNumber != 0L) {
        CardNumber = other.CardNumber;
      }
      if (other.ExpMonth != 0) {
        ExpMonth = other.ExpMonth;
      }
      if (other.ExpYear != 0) {
        ExpYear = other.ExpYear;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            CardNumber = input.ReadInt64();
            break;
          }
          case 16: {
            ExpMonth = input.ReadInt32();
            break;
          }
          case 24: {
            ExpYear = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            CardNumber = input.ReadInt64();
            break;
          }
          case 16: {
            ExpMonth = input.ReadInt32();
            break;
          }
          case 24: {
            ExpYear = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class OrderRequest : pb::IMessage<OrderRequest>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrderRequest> _parser = new pb::MessageParser<OrderRequest>(() => new OrderRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OrderRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AdventureWorks.AdventureworksReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderRequest(OrderRequest other) : this() {
      salesOrderId_ = other.salesOrderId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderRequest Clone() {
      return new OrderRequest(this);
    }

    /// <summary>Field number for the "sales_order_id" field.</summary>
    public const int SalesOrderIdFieldNumber = 1;
    private int salesOrderId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int SalesOrderId {
      get { return salesOrderId_; }
      set {
        salesOrderId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OrderRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OrderRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (SalesOrderId != other.SalesOrderId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (SalesOrderId != 0) hash ^= SalesOrderId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (SalesOrderId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SalesOrderId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (SalesOrderId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(SalesOrderId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (SalesOrderId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(SalesOrderId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OrderRequest other) {
      if (other == null) {
        return;
      }
      if (other.SalesOrderId != 0) {
        SalesOrderId = other.SalesOrderId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            SalesOrderId = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            SalesOrderId = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class OrderResponse : pb::IMessage<OrderResponse>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OrderResponse> _parser = new pb::MessageParser<OrderResponse>(() => new OrderResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OrderResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::AdventureWorks.AdventureworksReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderResponse(OrderResponse other) : this() {
      order_ = other.order_ != null ? other.order_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OrderResponse Clone() {
      return new OrderResponse(this);
    }

    /// <summary>Field number for the "order" field.</summary>
    public const int OrderFieldNumber = 1;
    private global::AdventureWorks.Order order_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::AdventureWorks.Order Order {
      get { return order_; }
      set {
        order_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OrderResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OrderResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Order, other.Order)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (order_ != null) hash ^= Order.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (order_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Order);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (order_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Order);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (order_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Order);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OrderResponse other) {
      if (other == null) {
        return;
      }
      if (other.order_ != null) {
        if (order_ == null) {
          Order = new global::AdventureWorks.Order();
        }
        Order.MergeFrom(other.Order);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (order_ == null) {
              Order = new global::AdventureWorks.Order();
            }
            input.ReadMessage(Order);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            if (order_ == null) {
              Order = new global::AdventureWorks.Order();
            }
            input.ReadMessage(Order);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
